controller_joint_names: ['', 'joint#1_finger1_abad', 'joint#2_finger1_flex1', 'joint#3_finger1_flex2', 'joint#4_finger2_flex1', 'joint#5_finger2_flex2', 'joint#6_finger3_abad', 'joint#7_finger3_flex1', 'joint#8_finger3_flex2', ]
